# Written by videoclip on Sun Jan 25 15:07:33 2026.
video_fps=auto
audio_format=opus
audio_bitrate=384k
font_size=24
osd_align=7
osd_outline=1.5
clean_filename=yes
litterbox=no
litterbox_expire=72h
custom_upload_command=
filename_template=%n_%s-%e
video_folder_path=V:\Videos\Clips\mpv
audio_folder_path=V:\Videos\Clips\mpv
video_quality=16
preset=slow
video_format=mp4
video_width=-2
video_height=-2
